# Generated by Django 3.0.2 on 2020-01-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('Lambda', models.FloatField()),
            ],
            options={
                'db_table': 'mengine',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.CharField(max_length=200)),
                ('mengine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_translation.MEngine')),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.CharField(max_length=200)),
                ('mengine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_translation.MEngine')),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
