# Generated by Django 3.0.2 on 2020-01-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_translation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='data_path',
        ),
        migrations.AddField(
            model_name='mengine',
            name='gtc',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='batch_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='buffer_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='cur_epoch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='epoch_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='epochs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='input_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='pix_acc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='pix_img_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='is_clip',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='is_gtc',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='is_iou',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='save_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='space',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='tmp_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mengine',
            name='Lambda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mengine',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mengine',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
