# Generated by Django 3.0.2 on 2020-02-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_translation', '0002_auto_20200131_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='tmp_epoch',
            field=models.IntegerField(null=True),
        ),
    ]
