# Generated by Django 3.0.2 on 2020-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_translation', '0003_train_tmp_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='epoch_time',
            field=models.FloatField(null=True),
        ),
    ]
