# Generated by Django 3.0.2 on 2020-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_translation', '0004_auto_20200203_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='is_iou',
            new_name='is_pix',
        ),
        migrations.AddField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='total_time',
            field=models.FloatField(null=True),
        ),
    ]
