# Generated by Django 3.0.2 on 2020-02-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_translation', '0006_mengine_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='pix_pre_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
