# Generated by Django 3.0.2 on 2020-02-16 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_translation', '0008_train_pix_base_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mengine',
            name='url',
        ),
        migrations.AddField(
            model_name='mengine',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
